// src/pages/Shame.jsx
import React, { useEffect } from "react";
import Stonkbar from "../components/Stonkbar";
import "../styles/Shame.css";
import Rex2021 from "../images/shame/rex3.jpg";

function Stonks() {
  useEffect(() => {
    document.title = "Stonks Hall of Shame";
  }, []);

  return (
    <div>
      <Stonkbar></Stonkbar>
      <br />
      <br />
      <br />
      <h1 className="text-4xl font-semibold">Stonks Hall of Shame</h1>
      <br></br>
      <br></br>
      <br></br>

      <h1 className="text-4xl font-semibold">2021</h1>
      <div className="text-xl font-semibold">
        <h3>Rex W.</h3>
        <h3>$AJAX/$CZOO</h3>
        <h3>Start Price: $11.52</h3>
        <h3>End Price: $6.04</h3>
      </div>
      <h3 className="text-red-500">-47.57%</h3>
      <p>
        $SPY was up <span className="text-green-500">&nbsp;28.79%&nbsp;</span>{" "}
        that year
      </p>
      <img
        src={Rex2021}
        className="flex content-center mx-auto"
        alt="Rex 2021"
        height={350}
        width={350}
      />
      <br></br>
      <br></br>
      <p>“Wait, I thought you said stonks only go up”</p>
      <br></br>
      <br></br>
      <br></br>
    </div>
  );
}

export default Stonks;

// src/routes/stonks/shame/+page.svelte
<script lang="ts">
	import Rex2021 from '../../../assets/stonkers/shame/rex3.jpg';
	import Poles2022 from '../../../assets/stonkers/shame/poles.jpg';
</script>

<h1 class="flex justify-center text-4xl py-8">Stonks Hall of Shame</h1>
<div class="py-4">
	<h1 class="text-3xl font-semibold flex justify-center">2021</h1>
	<div class="text-xl font-semibold text-center">
		<h3>Rex W.</h3>
		<h3>$AJAX/$CZOO</h3>
		<h3>Start Price: $11.52</h3>
		<h3>End Price: $6.04</h3>
		<h3 class="text-green-500 text-lg">-47.57%</h3>
		<h3 class="text-red-500 text-lg">
			$SPY was up <span class="text-green-500">28.79%</span> that year
		</h3>
	</div>
	<div>
		<img
			class="flex content-center mx-auto"
			src={Rex2021}
			alt="Rex 2021"
			height={400}
			width={500}
		/>
		<p class="text-lg text-center py-4">“Wait, I thought you said stonks only go up”</p>
	</div>
</div>

<div class="py-4">
	<h1 class="text-3xl font-semibold flex justify-center">2021</h1>
	<div class="text-xl font-semibold text-center">
		<h3>Alex P.</h3>
		<h3>$ROKU</h3>
		<h3>Start Price: $228.2</h3>
		<h3>End Price: $40.70</h3>
		<h3 class="text-green-500 text-lg">-82.16%</h3>
		<h3 class="text-red-500 text-lg">
			$SPY was down <span class="text-red-500">-19.48%</span> that year
		</h3>
	</div>
	<div>
		<img
			class="flex content-center mx-auto"
			src={Poles2022}
			alt="Poles 2022"
			height={400}
			width={500}
		/>
		<p class="text-lg text-center py-4">“I don’t even like dumbass Roku”</p>
	</div>
</div>

<div class="py-4">
	<h1 class="text-4xl font-semibold flex justify-center">2023</h1>
	<div class="text-xl font-semibold text-center">
		<h3>?</h3>
		<!-- <h3>Sean Flignor</h3>
		<h3>$IBM</h3>
		<h3>Start Price: $133.66</h3>
		<h3>End Price: $140.89</h3>
		<h3 class="text-green-500 text-lg">5.41%</h3>
	</div>
	<div>
		<img
			class="flex content-center mx-auto"
			src={Sean2022}
			alt="Sean2022"
			height={400}
			width={500}
		/>
		<p class="text-lg text-center py-4">
			“Water Covers Two-Thirds of the Earth… I cover the rest” -Deion Sanders
		</p> -->
	</div>
</div>
